name: task_manager_app
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  # service locator that allows to  inject blocs with required repositories and boxes
  get_it: ^7.6.4

  # Networking
  dio: ^5.4.0
  # decode Json Web Tokens and you can  know if a JWT is already expired.
  jwt_decoder: ^2.0.1

  # Local Storge
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Localization
  easy_localization: ^3.0.1

  # Responsive
  responsive_sizer: ^3.1.1

  # Animation
  loading_animation_widget: ^1.2.0+3
  animate_do: ^3.1.2

  # Firebase
  # firebase_core: ^2.25.4
  # firebase_auth: ^4.17.5
  # firebase_messaging: ^14.7.16

  # Notification
  # awesome_notifications: ^0.8.2

  # Images handling
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.0
  image_cropper: ^5.0.0
  image_picker: ^1.0.4

  # flutter secure storage to store data in secure storage.
  flutter_secure_storage: ^9.0.0

  # give you information about the application package
  package_info_plus: ^5.0.1

  # give you useful information about the device
  platform_device_id: ^1.0.1

  # provides a cross-platform (iOS, Android) API to request and check permissions.
  permission_handler: ^11.1.0

  # provides date/number formatting and parsing
  intl: ^0.18.0

  # provides common operations for manipulating paths
  path: ^1.8.1
  path_provider: ^2.0.11

  # clean and lightweight loading/toast widget for Flut
  flutter_easyloading: ^3.0.5

  # to do stuff when the Android back-button is tapped, as an alternative to `WillPopScope`
  back_button_interceptor: ^7.0.0

  # customize Flutter's  native splash screen with background color and splash image
  flutter_native_splash: ^2.2.9 # Android 12 issue

  # flutter package for easy implementation of curved navigation bar
  curved_navigation_bar: ^1.0.3

  # provides an easy way to add shimmer effect in Flutter project
  shimmer: ^3.0.0

  # restart the whole Flutter app with a single function call by using Native APIs.
  restart_app: ^1.2.1

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  http_parser: ^4.0.2
  #  To launch a URL
  url_launcher: ^6.3.0

  #  A PageView widget adjusting its height to currently displayed page.we use it here instead of carousel slider
  expandable_page_view: ^1.0.17

  # Flutter package to show beautiful dialogs
  awesome_dialog: ^3.2.1 #3.0.0

  #Flutter plugin for Google Sign-In
  google_sign_in: ^6.1.0

  # Flutter package to make a dotted border
  dotted_border: ^2.1.0

  fl_chart: ^0.69.0

  flutter_html: ^3.0.0-beta.2

dependency_overrides:
  win32: ^5.0.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices.
  flutter_lints: ^2.0.0

  # simplifies the task of updating your Flutter app's launcher icon.
  flutter_launcher_icons: "^0.13.1"

  # Colorize console output
  colorize: ^3.0.0

  # automatically generates TypeAdapters to store any class
  hive_generator: ^2.0.0

  # a buldi system for Dart code generation and modular compilation
  build_runner: ^2.3.3

  # change the name of your package
  change_app_package_name: ^1.1.0

  dropdown_button2: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
#  image_path: "assets/images/logo.png"

flutter_native_splash:
  color: "#061492"
#  image: assets/images/new_splash.png
  android: true
  ios: true
  android_12:
    color: "#061492"
#    image: assets/images/new_splash.png

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets(images, fonts and translations files) to your application, add an assets section, like this:
  assets:
#    - assets/images/
#    - assets/images/onboarding/
#    - assets/images/social_images/
#    - assets/images/appbar_images/
#    # - assets/svgs/
#    - assets/icons/
#    - assets/icons/drawer_icons/
    # - assets/svgs/


  # To add custom fonts to your application:
#  fonts:
#    - family: Nunito
#      fonts:
#        - asset: assets/fonts/Nunito-Regular.ttf
#          weight: 700
          # style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
